spring:
  profiles:
    active: local
  application:
    name: library-events-producer
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: ${TRUST_STORE_LOCATION}
        trust-store-password: ${TRUST_STORE_PASSWORD}
        key-store-location: ${KEY_STORE_LOCATION}
        key-store-password: ${KEY_STORE_PASSWORD}
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        security:
          protocol: SSL
          ssl.endpoint.identification.algorithm: 
        #acks: 1 // default is -1
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094